{% set name = "wxee" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wxee-{{ version }}.tar.gz
  sha256: e197df48c8b975fdc50793d2c554c9ec9617fa11ed262b2fec3b983e46f71042

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - earthengine-api
    - python >={{ python_min }}
    - rasterio
    - rioxarray >=0.3.0
    - requests
    - tqdm
    - xarray
    - joblib

test:
  requires:
    - python {{ python_min }}
  imports:
    - wxee

about:
  home: https://github.com/aazuspan/wxee
  summary: Earth Engine to xarray interface
  license: MIT
  license_file: LICENSE
  doc_url: https://wxee.readthedocs.io/

extra:
  recipe-maintainers:
    - aazuspan
