{% set name = "wxee" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wxee-{{ version }}.tar.gz
  sha256: c7f1d6e3cc82d1a06a70ccd5ecfe3621b9e91b1dd69ddd4a928601c793c0f476

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - earthengine-api
    - netcdf4
    - python >=3.7
    - rasterio
    - requests
    - tqdm
    - xarray
    - httplib2shim
    - joblib

test:
  imports:
    - wxee

about:
  home: https://github.com/aazuspan/wxee
  summary: Earth Engine to xarray interface
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://wxee.readthedocs.io/

extra:
  recipe-maintainers:
    - aazuspan
