{% set name = "wxee" %}
{% set version = "0.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wxee-{{ version }}.tar.gz
  sha256: 85f29f902270121e8d1e079bf4d7f3eb7770eac2bb2737a3cc230445bdd54699

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
  run:
    - earthengine-api
    - python >=3.8
    - rasterio
    - rioxarray >=0.3.0
    - requests
    - tqdm
    - xarray
    - joblib

test:
  imports:
    - wxee

about:
  home: https://github.com/aazuspan/wxee
  summary: Earth Engine to xarray interface
  license: MIT
  license_file: LICENSE
  doc_url: https://wxee.readthedocs.io/

extra:
  recipe-maintainers:
    - aazuspan
