{% set name = "wxee" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wxee-{{ version }}.tar.gz
  sha256: 5ad1f2e1c625e2b13ba81c50b84236bde35f7ab578791917a6c23ec0fe4e9f30

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - earthengine-api
    - python >={{ python_min }}
    - rasterio
    - rioxarray >=0.3.0
    - requests
    - tqdm
    - xarray
    - joblib

test:
  requires:
    - python {{ python_min }}
  imports:
    - wxee

about:
  home: https://github.com/aazuspan/wxee
  summary: Earth Engine to xarray interface
  license: MIT
  license_file: LICENSE
  doc_url: https://wxee.readthedocs.io/

extra:
  recipe-maintainers:
    - aazuspan
