{% set name = "wxee" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wxee-{{ version }}.tar.gz
  sha256: d80a0e633b8c4e4d09df74e65d1fea60203459d1502d49230e0e5ac7c1f72514

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - earthengine-api
    - netcdf4
    - python >=3.7
    - rasterio
    - requests
    - tqdm
    - xarray
    - httplib2shim
    - joblib

test:
  imports:
    - wxee

about:
  home: https://github.com/aazuspan/wxee
  summary: Earth Engine to xarray interface
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://wxee.readthedocs.io/

extra:
  recipe-maintainers:
    - aazuspan
