{% set name = "wxee" %}
{% set version = "0.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wxee-{{ version }}.tar.gz
  sha256: 8747440a3b0919c37324fc12f58c82b5754e78587c736b97ab4ecd9d43613355

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - earthengine-api
    - netcdf4
    - python >=3.7
    - rasterio
    - requests
    - tqdm
    - xarray
    - httplib2shim
    - joblib
    - plotly >=5.2.2

test:
  imports:
    - wxee

about:
  home: https://github.com/aazuspan/wxee
  summary: Earth Engine to xarray interface
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://wxee.readthedocs.io/

extra:
  recipe-maintainers:
    - aazuspan
